services:
  postgres:
    image: postgres:16-alpine
    container_name: inventory_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gs123123gs
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory_network

  api:
    build: .
    container_name: inventory_api_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=gs123123gs
    networks:
      - inventory_network

volumes:
  postgres_data:

networks:
  inventory_network: