spring.application.name=inventory

# Conectando direto no Postgres 18 do seu Windows
spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=postgres
spring.datasource.password=gs123123gs

# Cria as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console para ajudar a debugar
spring.jpa.show-sql=true
api.security.token.secret=minha_senha_super_secreta_aqui_123

# Corrige problemas de HTTPS reverso no Render para o Swagger funcionar
server.forward-headers-strategy=framework